USE master

CREATE DATABASE Prueba_ControlBox


CREATE TABLE CORRESPONSALES(
	COR_CORRESPONSAL_ID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COR_NOMBRE VARCHAR(150) NOT NULL
)


CREATE TABLE OFICINAS(
	OFI_ID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	OFI_CORRESPONSAL_ID BIGINT NOT NULL,
	OFI_NOMBRE VARCHAR(150) NOT NULL
)


ALTER TABLE OFICINAS
   ADD CONSTRAINT FK_OFICINAS_CORRESPONSALES FOREIGN KEY (OFI_CORRESPONSAL_ID)
      REFERENCES CORRESPONSALES (COR_CORRESPONSAL_ID)