USE [Prueba_ControlBox]
GO
SET IDENTITY_INSERT [dbo].[CORRESPONSALES] ON 
GO
INSERT [dbo].[CORRESPONSALES] ([COR_CORRESPONSAL_ID], [COR_NOMBRE]) VALUES (6, N'Sureste')
GO
INSERT [dbo].[CORRESPONSALES] ([COR_CORRESPONSAL_ID], [COR_NOMBRE]) VALUES (8, N'Guayabal')
GO
INSERT [dbo].[CORRESPONSALES] ([COR_CORRESPONSAL_ID], [COR_NOMBRE]) VALUES (9, N'Aguachica')
GO
INSERT [dbo].[CORRESPONSALES] ([COR_CORRESPONSAL_ID], [COR_NOMBRE]) VALUES (10, N'San Antonio')
GO
SET IDENTITY_INSERT [dbo].[CORRESPONSALES] OFF
GO
SET IDENTITY_INSERT [dbo].[OFICINAS] ON 
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (11, 8, N'San Jose 2')
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (12, 6, N'San Juan')
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (13, 9, N'Prado 2')
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (14, 9, N'Verde')
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (15, 8, N'Agence principale')
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (16, 10, N'Alto prado')
GO
INSERT [dbo].[OFICINAS] ([OFI_ID], [OFI_CORRESPONSAL_ID], [OFI_NOMBRE]) VALUES (17, 6, N'San Carlos')
GO
SET IDENTITY_INSERT [dbo].[OFICINAS] OFF
GO
